import {PT_Sans } from "next/font/google";
import "./globals.css";



const Pt = PT_Sans({
  variable: "--font-pt",
  weight: ["400"],
  subsets: ["latin"]
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Pt.variable} font-sans bg-background text-foreground`}>
        {children}
      </body>
    </html>
  );
}
